# version: '3.9'

services:
  db:
    image: postgres:latest
    container_name: todo_app_postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: todo
      PG_DATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - .db_data:/var/lib/postgresql/data